apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: docker.io/vinaykale/client
      context: client
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
      docker:
        dockerfile: dockerfile
    - image: docker.io/vinaykale/comments
      context: comments
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
      docker:
        dockerfile: dockerfile
    - image: docker.io/vinaykale/event-bus
      context: event-bus
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
      docker:
        dockerfile: dockerfile
    - image: docker.io/vinaykale/moderation
      context: moderation
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker.io/vinaykale/posts
      context: posts
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
      docker:
        dockerfile: dockerfile
    - image: docker.io/vinaykale/query
      context: query
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
      docker:
        dockerfile: dockerfile
